---
- name: Run arbitrary command against hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Run command
      ansible.builtin.command:  "{{ run_cmd }}"
      register: command_results
    
    - name: Display command results
      ansible.builtin.debug:
        var: command_results
...
