---
- name: Construct inventoryies from CMDB queries
  hosts: localhost
  gather_facts: true
  become: false
  pre_tasks:
    - name: Include postgresql vars to query database
      ansible.builtin.include_vars:
        dir: vars/

    - name: Get AAP token
      ansible.controller.token:
        controller_host: "{{ aaphost }}"
        controller_password: "{{ aappass }}"
        controller_username: "{{ aapuser }}"
        scope: 'write'
        validate_certs: true
      register: aaptoken

  tasks:
    - name: Query database for hosts in {{ site_abbreviation }}
      community.postgresql.postgresql_query:
        db: "{{ dbname }}"
        login_host: "{{ dbhost }}"
        login_user: "{{ dbuser }}"
        login_password: "{{ dbpassword }}"
        port: "{{ dbport }}"
        query: SELECT * FROM cmdb.hosts WHERE site LIKE '{{ site_abbreviation }}'
      register: sql_query_results
    
    - name: Create fact with just hostnames
      ansible.builtin.set_fact:
        site_hosts: "{{ site_hosts | default([]) + [hosts] }}"
      loop: "{{ sql_query_results['query_result'] | map(attribute='host') | list}}"
      loop_control:
        loop_var: hosts

    - name: Create Inventory for HPSA
      ansible.controller.inventory:
        controller_host: "{{ aaphost }}"
        controller_oauthtoken: "{{ aaptoken['ansible_facts']['controller_token']['token'] }}"
        name: "HPSA {{ site_abbreviation }} Inventory"
        description: "{{ site_abbreviation }} Hosts for HPSA Execution"
        organization: 'Texas Roadracing'
    
    - name: Add hosts from Query Results to inventory
      ansible.controller.host:
        controller_host: "{{ aaphost }}"
        controller_oauthtoken: "{{ aaptoken['ansible_facts']['controller_token']['token'] }}"
        name: "{{ item }}"
        inventory: "HPSA {{ site_abbreviation}} Inventory"
      loop: "{{ site_hosts }}"

    - name: Launch job in AAP against hostgroup using "{{ site_abbreviation}}" instance group
      ansible.controller.job_launch:
        controller_host: "{{ aaphost }}"
        controller_oauthtoken: "{{ aaptoken['ansible_facts']['controller_token']['token'] }}"
        job_template: 'Run command against hosts'
        inventory: "HPSA {{ site_abbreviation }} Inventory"
        extra_vars:
          run_cmd: 'df -h'
        instance_groups:
          - "{{ site_abbreviation }}_IG"
...
